server:
  port: 8880
spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://${pro.ip}:3306/miui?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: Lx@520zx
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 300
        initialSize: 5
        maxWait: 60000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'controller'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      slave:
        url: jdbc:mysql://${pro.ip}:3306/books?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: Lx@520zx
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 300
        initialSize: 5
        maxWait: 60000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'controller'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      slave1:
        url: jdbc:mysql://${pro.ip}:3306/store?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: Lx@520zx
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 300
        initialSize: 5
        maxWait: 60000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'controller'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
  redis:
    host: ${pro.ip}
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1
    port: 6699
    database: 0
    timeout: 0
  security:
    user:
      name: lx
      password: zx
  application:
    name: service-invoke
#  main:
#    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.invoke.model
  configuration:
    local-cache-scope: statement
    cache-enabled: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  config: classpath:logback-spring.xml
pro:
  ip: 193.112.113.194
#eureka:
#  client:
#    service-url:
#      defaultZone:  http://lx:zx@${pro.ip}:8766/eureka/  # 指定注册中心的地址
#  instance:
#    prefer-ip-address: true