server:
  port: 17080
spring:
  application:
    name: service-gateway
  redis:
    host: 193.112.113.194
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1
    port: 6699
    database: 0
    timeout: 5000
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone:  http://lx:zx@localhost:8766/eureka/  # 指定注册中心的地址
  instance:
    prefer-ip-address: true
