server:
  port: 17080
spring:
  application:
    name: service-gateway
  redis:
    host: 193.112.113.194
    port: 6379
    database: 0
    timeout: 5000
    password: lovecache
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      port: 8500
      host: 192.168.81.129
      discovery:
        instance-id: ${spring.application.name}
        prefer-ip-address: true


