server:
  port: 17080
spring:
  redis:
    host: ${pro.ip}
    port: 6379
    database: 0
    timeout: 5000
    password: lovecache
  application:
    name: service-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      host: ${pro.ip}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}
        prefer-ip-address: true
pro:
  ip: 193.112.113.194