server:
  port: 8766
spring:
  application:
    name: eureka-master
  security:
    user:
      name: lx
      password: zx
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    hostname: master-discovery
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://lx:zx@193.112.113.194:8766/eureka/
